<?php

// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Release tags as rows, kept by an admin, so the bugs desk's "Fixed in" is a
 * choice and not free text (docs/specs/contact-and-support.md §9, owner
 * 2026-09-08). Seeded with the one release that exists.
 */
final class Version20260908160000 extends AbstractMigration
{
    #[\Override]
    public function getDescription(): string
    {
        return 'release_tag: the releases the bugs desk may say a fix landed in';
    }

    #[\Override]
    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE release_tag (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tag VARCHAR(64) NOT NULL,
                released_at DATE DEFAULT NULL,
                note TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_release_tag_tag ON release_tag (tag)');
        $this->addSql("COMMENT ON COLUMN release_tag.released_at IS '(DC2Type:date_immutable)'");
        $this->addSql("COMMENT ON COLUMN release_tag.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("INSERT INTO release_tag (tag, released_at, note, created_at) VALUES ('v0.8.0-beta', '2026-08-28', 'The first tagged release.', NOW())");
    }

    #[\Override]
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE release_tag');
    }
}
