<?php

// SPDX-License-Identifier: AGPL-3.0-only

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Account statements of reasons whose email did not go out
 * (docs/specs/account-and-auth.md §6.8), kept whole until an administrator
 * sends them again or discards them. `user_id` is the account while it
 * exists; its foreign key deletes the row with the account, and it is NULL
 * after a removal for a breach, when the account is already gone.
 */
final class Version20261009050100 extends AbstractMigration
{
    #[\Override]
    public function getDescription(): string
    {
        return 'unsent_statement: account statements of reasons the mail transport refused';
    }

    #[\Override]
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE unsent_statement (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT DEFAULT NULL,
            address VARCHAR(180) NOT NULL,
            name VARCHAR(100) NOT NULL,
            locale VARCHAR(5) DEFAULT NULL,
            time_zone VARCHAR(64) DEFAULT NULL,
            statement JSONB NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            attempts INT NOT NULL,
            last_attempt_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX idx_unsent_statement_user ON unsent_statement (user_id)');
        $this->addSql('ALTER TABLE unsent_statement ADD CONSTRAINT fk_unsent_statement_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON TABLE unsent_statement IS 'A statement of reasons for an account decision whose email did not go out, kept whole until an administrator sends it again or gives up on it.'");
        $this->addSql("COMMENT ON COLUMN unsent_statement.user_id IS 'The account while it exists; the row goes with it. NULL after a removal for a breach.'");
        $this->addSql("COMMENT ON COLUMN unsent_statement.statement IS 'The statement as decided (StatementOfReasons::toArray): decision, ground, facts, reference.'");
    }

    #[\Override]
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE unsent_statement');
    }
}
