<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701100312 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE world_continent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_45EB256577153098 ON world_continent (code)');
        $this->addSql('CREATE TABLE world_country (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, iso2 VARCHAR(2) NOT NULL, iso3 VARCHAR(3) NOT NULL, name VARCHAR(120) NOT NULL, continent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BC36E7311B6F9774 ON world_country (iso2)');
        $this->addSql('CREATE INDEX IDX_BC36E731921F4C77 ON world_country (continent_id)');
        $this->addSql('CREATE TABLE world_subdivision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(10) NOT NULL, name VARCHAR(160) NOT NULL, type VARCHAR(64) DEFAULT NULL, level SMALLINT DEFAULT 1 NOT NULL, country_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C235E2C577153098 ON world_subdivision (code)');
        $this->addSql('CREATE INDEX IDX_C235E2C5727ACA70 ON world_subdivision (parent_id)');
        $this->addSql('CREATE INDEX idx_subdivision_country ON world_subdivision (country_id)');
        $this->addSql('ALTER TABLE world_country ADD CONSTRAINT FK_BC36E731921F4C77 FOREIGN KEY (continent_id) REFERENCES world_continent (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE world_subdivision ADD CONSTRAINT FK_C235E2C5F92F3E70 FOREIGN KEY (country_id) REFERENCES world_country (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE world_subdivision ADD CONSTRAINT FK_C235E2C5727ACA70 FOREIGN KEY (parent_id) REFERENCES world_subdivision (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD country_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9F92F3E70 FOREIGN KEY (country_id) REFERENCES world_country (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_1483A5E9F92F3E70 ON users (country_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA topology');
        $this->addSql('ALTER TABLE world_country DROP CONSTRAINT FK_BC36E731921F4C77');
        $this->addSql('ALTER TABLE world_subdivision DROP CONSTRAINT FK_C235E2C5F92F3E70');
        $this->addSql('ALTER TABLE world_subdivision DROP CONSTRAINT FK_C235E2C5727ACA70');
        $this->addSql('DROP TABLE world_continent');
        $this->addSql('DROP TABLE world_country');
        $this->addSql('DROP TABLE world_subdivision');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9F92F3E70');
        $this->addSql('DROP INDEX IDX_1483A5E9F92F3E70');
        $this->addSql('ALTER TABLE users DROP country_id');
    }
}
