<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701194258 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin_action_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(40) NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_id INT DEFAULT NULL, target_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7AFB500010DAF24A ON admin_action_log (actor_id)');
        $this->addSql('CREATE INDEX IDX_7AFB50006C066AFE ON admin_action_log (target_user_id)');
        $this->addSql('ALTER TABLE admin_action_log ADD CONSTRAINT FK_7AFB500010DAF24A FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE admin_action_log ADD CONSTRAINT FK_7AFB50006C066AFE FOREIGN KEY (target_user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA topology');
        $this->addSql('ALTER TABLE admin_action_log DROP CONSTRAINT FK_7AFB500010DAF24A');
        $this->addSql('ALTER TABLE admin_action_log DROP CONSTRAINT FK_7AFB50006C066AFE');
        $this->addSql('DROP TABLE admin_action_log');
    }
}
