<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * submission + change_history schema (moderation spec §6/§9), plus
 * region.country_code so submissions and regions can be filtered/matched
 * by country from day one.
 */
final class Version20260704222148 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add submission + change_history tables; region.country_code';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE submission (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(8) NOT NULL, letter VARCHAR(1) NOT NULL, item_id BIGINT DEFAULT NULL, user_id BIGINT NOT NULL, status VARCHAR(12) NOT NULL, title VARCHAR(200) NOT NULL, geom geometry(Geometry, 4326) NOT NULL, country_code VARCHAR(2) NOT NULL, region_id BIGINT DEFAULT NULL, changes JSONB NOT NULL, payload JSONB NOT NULL, decision_note TEXT DEFAULT NULL, decided_by BIGINT DEFAULT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_submission_status ON submission (status)');
        $this->addSql('CREATE INDEX idx_submission_country ON submission (country_code)');
        $this->addSql('CREATE INDEX idx_submission_region ON submission (region_id)');
        $this->addSql('CREATE INDEX idx_submission_item ON submission (item_id)');
        $this->addSql('CREATE INDEX idx_submission_user ON submission (user_id)');
        $this->addSql('CREATE INDEX idx_submission_geom ON submission USING GIST (geom)');
        $this->addSql('CREATE TABLE change_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, item_id BIGINT NOT NULL, submission_id BIGINT DEFAULT NULL, field VARCHAR(80) NOT NULL, old_value JSONB DEFAULT NULL, new_value JSONB DEFAULT NULL, changed_by BIGINT NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_history_item_time ON change_history (item_id, changed_at)');
        $this->addSql("ALTER TABLE region ADD country_code VARCHAR(2) DEFAULT '' NOT NULL");
        $this->addSql("UPDATE region SET country_code = 'BE' WHERE slug = 'wallonia'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE region DROP country_code');
        $this->addSql('DROP TABLE change_history');
        $this->addSql('DROP TABLE submission');
    }
}
