<?php

// SPDX-License-Identifier: AGPL-3.0-only

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Create country_interest table for recording which countries people are asking for.
 */
final class Version20260729203612 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create country_interest table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE country_interest (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT NOT NULL, country_code VARCHAR(2) NOT NULL, willing_to_curate BOOLEAN DEFAULT false NOT NULL, note VARCHAR(280) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_country_interest_user_cc ON country_interest (user_id, country_code)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE country_interest');
    }
}
