<?php

// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Create curator_application table for country-scoped curator signup
 * (moderation-and-contribution.md).
 *
 * The partial unique index is the concurrency guard for "one pending
 * application per person per country" — the service's own hasPending() check
 * is UX (a friendly error before a flush), this index is the invariant that
 * holds even under a race. Doctrine's mapping attributes cannot express a
 * partial index, so it is hand-added here rather than left to the diff tool.
 *
 * osm_exists is nullable tri-state, not boolean: null = never checked or OSM
 * was unreachable, true = the handle was found, false = checked and absent.
 * Collapsing "absent" and "never checked" into one value would let a
 * fabricated handle render as "verified" on the review screen.
 */
final class Version20260729212853 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create curator_application table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE curator_application (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT NOT NULL, country_code VARCHAR(2) NOT NULL, requested_region_id BIGINT DEFAULT NULL, osm_username VARCHAR(64) DEFAULT NULL, osm_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, osm_exists BOOLEAN DEFAULT NULL, osm_changeset_count INT DEFAULT NULL, about TEXT NOT NULL, status VARCHAR(12) NOT NULL, decided_by BIGINT DEFAULT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, decision_note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_curator_application_status ON curator_application (status)');
        $this->addSql("CREATE UNIQUE INDEX uniq_curator_application_pending
                       ON curator_application (user_id, country_code)
                       WHERE status = 'pending'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX uniq_curator_application_pending');
        $this->addSql('DROP TABLE curator_application');
    }
}
