<?php

// SPDX-License-Identifier: AGPL-3.0-only

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The 19 countries live before one-command onboarding, as rows.
 *
 * Generated once from COUNTRY_CONFIG, COUNTRY_L2, ONBOARDED_REGIONS,
 * COUNTRY_BY_REGION, scope.js TZ_COUNTRY and the region section of
 * messages.*.yaml, which the same change deletes, so the values are inlined.
 * Spain follows ONBOARDED_REGIONS.
 * Idempotent: a test replays it.
 */
final class Version20261005120100 extends AbstractMigration
{
    /** @var array<string, array{name: string, subtype: string, bbox: list<float>|null, labels: array<string, string>, timezones: list<string>}> */
    public const array COUNTRIES = [
        'AU' => [
            'name' => 'Australia',
            'subtype' => 'region',
            'bbox' => [112.82, -54.88, 159.36, -9.12],
            'labels' => [
                'en' => 'All Australia',
                'fr' => 'Toute l\'Australie',
                'nl' => 'Heel Australië',
                'de' => 'Ganz Australien',
                'es' => 'Toda Australia',
            ],
            'timezones' => ['Australia/Sydney', 'Australia/Melbourne', 'Australia/Brisbane', 'Australia/Perth', 'Australia/Adelaide', 'Australia/Hobart', 'Australia/Darwin', 'Australia/Canberra', 'Australia/Broken_Hill', 'Australia/Lindeman', 'Australia/Lord_Howe', 'Australia/Eucla'],
        ],
        'BE' => [
            'name' => 'Belgium',
            'subtype' => 'region',
            'bbox' => [2.5, 49.4, 6.5, 51.6],
            'labels' => [
                'en' => 'All Belgium',
                'fr' => 'Toute la Belgique',
                'nl' => 'Heel België',
                'de' => 'Ganz Belgien',
                'es' => 'Toda Bélgica',
            ],
            'timezones' => ['Europe/Brussels'],
        ],
        'CA' => [
            'name' => 'Canada',
            'subtype' => 'region',
            'bbox' => [-139.06, 41.68, -57.1, 62.59],
            'labels' => [
                'en' => 'All Canada',
                'fr' => 'Tout le Canada',
                'nl' => 'Heel Canada',
                'de' => 'Ganz Kanada',
                'es' => 'Todo Canadá',
            ],
            'timezones' => ['America/Vancouver', 'America/Toronto', 'America/Montreal'],
        ],
        'CH' => [
            'name' => 'Switzerland',
            'subtype' => 'region',
            'bbox' => [5.86, 45.72, 10.59, 47.91],
            'labels' => [
                'en' => 'All Switzerland',
                'fr' => 'Toute la Suisse',
                'nl' => 'Heel Zwitserland',
                'de' => 'Ganze Schweiz',
                'es' => 'Toda Suiza',
            ],
            'timezones' => ['Europe/Zurich'],
        ],
        'CL' => [
            'name' => 'Chile',
            'subtype' => 'region',
            'bbox' => [-109.55, -56.62, -66.32, -17.4],
            'labels' => [
                'en' => 'All Chile',
                'fr' => 'Tout le Chili',
                'nl' => 'Heel Chili',
                'de' => 'Ganz Chile',
                'es' => 'Todo Chile',
            ],
            'timezones' => ['America/Santiago', 'Pacific/Easter'],
        ],
        'CO' => [
            'name' => 'Colombia',
            'subtype' => 'region',
            'bbox' => [-81.84, -4.33, -66.75, 13.49],
            'labels' => [
                'en' => 'All Colombia',
                'fr' => 'Toute la Colombie',
                'nl' => 'Heel Colombia',
                'de' => 'Ganz Kolumbien',
                'es' => 'Toda Colombia',
            ],
            'timezones' => ['America/Bogota'],
        ],
        'DE' => [
            'name' => 'Germany',
            'subtype' => 'region',
            'bbox' => [5.77, 47.17, 15.14, 55.16],
            'labels' => [
                'en' => 'All Germany',
                'fr' => 'Toute l\'Allemagne',
                'nl' => 'Heel Duitsland',
                'de' => 'Ganz Deutschland',
                'es' => 'Toda Alemania',
            ],
            'timezones' => ['Europe/Berlin', 'Europe/Busingen'],
        ],
        'ES' => [
            'name' => 'Spain',
            'subtype' => 'region',
            'bbox' => [-18.26, 27.54, 4.43, 43.89],
            'labels' => [
                'en' => 'All Spain',
                'fr' => 'Toute l\'Espagne',
                'nl' => 'Heel Spanje',
                'de' => 'Ganz Spanien',
                'es' => 'Toda España',
            ],
            'timezones' => ['Europe/Madrid', 'Atlantic/Canary', 'Africa/Ceuta'],
        ],
        'FR' => [
            'name' => 'France',
            'subtype' => 'region',
            'bbox' => [-5.24, 41.23, 9.66, 51.19],
            'labels' => [
                'en' => 'All France',
                'fr' => 'Toute la France',
                'nl' => 'Heel Frankrijk',
                'de' => 'Ganz Frankreich',
                'es' => 'Toda Francia',
            ],
            'timezones' => ['Europe/Paris'],
        ],
        'GB' => [
            'name' => 'United Kingdom',
            'subtype' => 'region',
            'bbox' => [-8.75, 49.78, 1.86, 60.96],
            'labels' => [
                'en' => 'All of the UK',
                'fr' => 'Tout le Royaume-Uni',
                'nl' => 'Heel het Verenigd Koninkrijk',
                'de' => 'Gesamtes Vereinigtes Königreich',
                'es' => 'Todo el Reino Unido',
            ],
            'timezones' => ['Europe/London', 'Europe/Belfast'],
        ],
        'IT' => [
            'name' => 'Italy',
            'subtype' => 'region',
            'bbox' => [6.53, 35.39, 18.62, 47.19],
            'labels' => [
                'en' => 'All Italy',
                'fr' => 'Toute l\'Italie',
                'nl' => 'Heel Italië',
                'de' => 'Ganz Italien',
                'es' => 'Toda Italia',
            ],
            'timezones' => ['Europe/Rome'],
        ],
        'JP' => [
            'name' => 'Japan',
            'subtype' => 'region',
            'bbox' => [122.83, 23.95, 154.09, 45.62],
            'labels' => [
                'en' => 'All Japan',
                'fr' => 'Tout le Japon',
                'nl' => 'Heel Japan',
                'de' => 'Ganz Japan',
                'es' => 'Todo Japón',
            ],
            'timezones' => ['Asia/Tokyo'],
        ],
        'LU' => [
            'name' => 'Luxembourg',
            'subtype' => 'country',
            'bbox' => [5.7, 49.4, 6.6, 50.2],
            'labels' => [
                'en' => 'All Luxembourg',
                'fr' => 'Tout le Luxembourg',
                'nl' => 'Heel Luxemburg',
                'de' => 'Ganz Luxemburg',
                'es' => 'Todo Luxemburgo',
            ],
            'timezones' => ['Europe/Luxembourg'],
        ],
        'NL' => [
            'name' => 'Netherlands',
            'subtype' => 'region',
            'bbox' => [3.2, 50.7, 7.3, 53.6],
            'labels' => [
                'en' => 'All Netherlands',
                'fr' => 'Tous les Pays-Bas',
                'nl' => 'Heel Nederland',
                'de' => 'Gesamte Niederlande',
                'es' => 'Todos los Países Bajos',
            ],
            'timezones' => ['Europe/Amsterdam'],
        ],
        'NZ' => [
            'name' => 'New Zealand',
            'subtype' => 'region',
            'bbox' => [-176.99, -47.39, 178.68, -34.29],
            'labels' => [
                'en' => 'All New Zealand',
                'fr' => 'Toute la Nouvelle-Zélande',
                'nl' => 'Heel Nieuw-Zeeland',
                'de' => 'Ganz Neuseeland',
                'es' => 'Toda Nueva Zelanda',
            ],
            'timezones' => ['Pacific/Auckland', 'Pacific/Chatham'],
        ],
        'RW' => [
            'name' => 'Rwanda',
            'subtype' => 'region',
            'bbox' => [28.76, -2.94, 31.0, -0.95],
            'labels' => [
                'en' => 'All Rwanda',
                'fr' => 'Tout le Rwanda',
                'nl' => 'Heel Rwanda',
                'de' => 'Ganz Ruanda',
                'es' => 'Todo Ruanda',
            ],
            'timezones' => ['Africa/Kigali'],
        ],
        'SI' => [
            'name' => 'Slovenia',
            'subtype' => 'country',
            'bbox' => [13.28, 45.32, 16.7, 46.98],
            'labels' => [
                'en' => 'All Slovenia',
                'fr' => 'Toute la Slovénie',
                'nl' => 'Heel Slovenië',
                'de' => 'Ganz Slowenien',
                'es' => 'Toda Eslovenia',
            ],
            'timezones' => ['Europe/Ljubljana'],
        ],
        'US' => [
            'name' => 'United States',
            'subtype' => 'region',
            'bbox' => [-124.6, 32.4, -101.9, 42.1],
            'labels' => [
                'en' => 'All the US',
                'fr' => 'Tous les États-Unis',
                'nl' => 'Heel de VS',
                'de' => 'Gesamte USA',
                'es' => 'Todo Estados Unidos',
            ],
            'timezones' => ['America/Los_Angeles', 'America/Denver'],
        ],
        'ZA' => [
            'name' => 'South Africa',
            'subtype' => 'region',
            'bbox' => [16.35, -47.08, 38.1, -22.03],
            'labels' => [
                'en' => 'All South Africa',
                'fr' => 'Toute l\'Afrique du Sud',
                'nl' => 'Heel Zuid-Afrika',
                'de' => 'Ganz Südafrika',
                'es' => 'Toda Sudáfrica',
            ],
            'timezones' => ['Africa/Johannesburg'],
        ],
    ];

    /** @var array<string, string> Geofabrik extract => country */
    public const array EXTRACTS = [
        'africa/rwanda' => 'RW',
        'africa/south-africa' => 'ZA',
        'asia/japan' => 'JP',
        'australia-oceania/australia' => 'AU',
        'australia-oceania/new-zealand' => 'NZ',
        'europe/belgium' => 'BE',
        'europe/france' => 'FR',
        'europe/germany' => 'DE',
        'europe/great-britain' => 'GB',
        'europe/ireland-and-northern-ireland' => 'GB',
        'europe/italy' => 'IT',
        'europe/luxembourg' => 'LU',
        'europe/netherlands' => 'NL',
        'europe/slovenia' => 'SI',
        'europe/spain' => 'ES',
        'europe/switzerland' => 'CH',
        'north-america/canada/british-columbia' => 'CA',
        'north-america/canada/quebec' => 'CA',
        'north-america/us/california' => 'US',
        'north-america/us/colorado' => 'US',
        'south-america/chile' => 'CL',
        'south-america/colombia' => 'CO',
    ];

    /** @var array<string, array<string, string>> region slug => locale => label */
    public const array REGION_LABELS = [
        'wallonia' => [
            'en' => 'Wallonia',
            'fr' => 'Wallonie',
            'nl' => 'Wallonië',
            'de' => 'Wallonien',
            'es' => 'Valonia',
        ],
        'flanders' => [
            'en' => 'Flanders',
            'fr' => 'Flandre',
            'nl' => 'Vlaanderen',
            'de' => 'Flandern',
            'es' => 'Flandes',
        ],
        'brussels' => [
            'en' => 'Brussels',
            'fr' => 'Bruxelles',
            'nl' => 'Brussel',
            'de' => 'Brüssel',
            'es' => 'Bruselas',
        ],
        'drenthe' => [
            'en' => 'Drenthe',
            'fr' => 'Drenthe',
            'nl' => 'Drenthe',
            'de' => 'Drenthe',
            'es' => 'Drente',
        ],
        'flevoland' => [
            'en' => 'Flevoland',
            'fr' => 'Flevoland',
            'nl' => 'Flevoland',
            'de' => 'Flevoland',
            'es' => 'Flevolanda',
        ],
        'friesland' => [
            'en' => 'Friesland',
            'fr' => 'Frise',
            'nl' => 'Friesland',
            'de' => 'Friesland',
            'es' => 'Frisia',
        ],
        'gelderland' => [
            'en' => 'Gelderland',
            'fr' => 'Gueldre',
            'nl' => 'Gelderland',
            'de' => 'Gelderland',
            'es' => 'Güeldres',
        ],
        'groningen' => [
            'en' => 'Groningen',
            'fr' => 'Groningue',
            'nl' => 'Groningen',
            'de' => 'Groningen',
            'es' => 'Groninga',
        ],
        'limburg-nl' => [
            'en' => 'Limburg',
            'fr' => 'Limbourg',
            'nl' => 'Limburg',
            'de' => 'Limburg',
            'es' => 'Limburgo',
        ],
        'noord-brabant' => [
            'en' => 'North Brabant',
            'fr' => 'Brabant-Septentrional',
            'nl' => 'Noord-Brabant',
            'de' => 'Nordbrabant',
            'es' => 'Brabante Septentrional',
        ],
        'noord-holland' => [
            'en' => 'North Holland',
            'fr' => 'Hollande-Septentrionale',
            'nl' => 'Noord-Holland',
            'de' => 'Nordholland',
            'es' => 'Holanda Septentrional',
        ],
        'overijssel' => [
            'en' => 'Overijssel',
            'fr' => 'Overijssel',
            'nl' => 'Overijssel',
            'de' => 'Overijssel',
            'es' => 'Overijssel',
        ],
        'utrecht' => [
            'en' => 'Utrecht',
            'fr' => 'Utrecht',
            'nl' => 'Utrecht',
            'de' => 'Utrecht',
            'es' => 'Utrecht',
        ],
        'zeeland' => [
            'en' => 'Zeeland',
            'fr' => 'Zélande',
            'nl' => 'Zeeland',
            'de' => 'Zeeland',
            'es' => 'Zelanda',
        ],
        'zuid-holland' => [
            'en' => 'South Holland',
            'fr' => 'Hollande-Méridionale',
            'nl' => 'Zuid-Holland',
            'de' => 'Südholland',
            'es' => 'Holanda Meridional',
        ],
        'baden-wurttemberg' => [
            'en' => 'Baden-Württemberg',
            'fr' => 'Bade-Wurtemberg',
            'nl' => 'Baden-Württemberg',
            'de' => 'Baden-Württemberg',
            'es' => 'Baden-Wurtemberg',
        ],
        'bayern' => [
            'en' => 'Bavaria',
            'fr' => 'Bavière',
            'nl' => 'Beieren',
            'de' => 'Bayern',
            'es' => 'Baviera',
        ],
        'berlin' => [
            'en' => 'Berlin',
            'fr' => 'Berlin',
            'nl' => 'Berlijn',
            'de' => 'Berlin',
            'es' => 'Berlín',
        ],
        'brandenburg' => [
            'en' => 'Brandenburg',
            'fr' => 'Brandebourg',
            'nl' => 'Brandenburg',
            'de' => 'Brandenburg',
            'es' => 'Brandeburgo',
        ],
        'bremen' => [
            'en' => 'Bremen',
            'fr' => 'Brême',
            'nl' => 'Bremen',
            'de' => 'Bremen',
            'es' => 'Bremen',
        ],
        'hamburg' => [
            'en' => 'Hamburg',
            'fr' => 'Hambourg',
            'nl' => 'Hamburg',
            'de' => 'Hamburg',
            'es' => 'Hamburgo',
        ],
        'hessen' => [
            'en' => 'Hesse',
            'fr' => 'Hesse',
            'nl' => 'Hessen',
            'de' => 'Hessen',
            'es' => 'Hesse',
        ],
        'mecklenburg-vorpommern' => [
            'en' => 'Mecklenburg-Western Pomerania',
            'fr' => 'Mecklembourg-Poméranie-Occidentale',
            'nl' => 'Mecklenburg-Voor-Pommeren',
            'de' => 'Mecklenburg-Vorpommern',
            'es' => 'Mecklemburgo-Pomerania Occidental',
        ],
        'niedersachsen' => [
            'en' => 'Lower Saxony',
            'fr' => 'Basse-Saxe',
            'nl' => 'Nedersaksen',
            'de' => 'Niedersachsen',
            'es' => 'Baja Sajonia',
        ],
        'nordrhein-westfalen' => [
            'en' => 'North Rhine-Westphalia',
            'fr' => 'Rhénanie-du-Nord-Westphalie',
            'nl' => 'Noordrijn-Westfalen',
            'de' => 'Nordrhein-Westfalen',
            'es' => 'Renania del Norte-Westfalia',
        ],
        'rheinland-pfalz' => [
            'en' => 'Rhineland-Palatinate',
            'fr' => 'Rhénanie-Palatinat',
            'nl' => 'Rijnland-Palts',
            'de' => 'Rheinland-Pfalz',
            'es' => 'Renania-Palatinado',
        ],
        'saarland' => [
            'en' => 'Saarland',
            'fr' => 'Sarre',
            'nl' => 'Saarland',
            'de' => 'Saarland',
            'es' => 'Sarre',
        ],
        'sachsen' => [
            'en' => 'Saxony',
            'fr' => 'Saxe',
            'nl' => 'Saksen',
            'de' => 'Sachsen',
            'es' => 'Sajonia',
        ],
        'sachsen-anhalt' => [
            'en' => 'Saxony-Anhalt',
            'fr' => 'Saxe-Anhalt',
            'nl' => 'Saksen-Anhalt',
            'de' => 'Sachsen-Anhalt',
            'es' => 'Sajonia-Anhalt',
        ],
        'schleswig-holstein' => [
            'en' => 'Schleswig-Holstein',
            'fr' => 'Schleswig-Holstein',
            'nl' => 'Sleeswijk-Holstein',
            'de' => 'Schleswig-Holstein',
            'es' => 'Schleswig-Holstein',
        ],
        'thuringen' => [
            'en' => 'Thuringia',
            'fr' => 'Thuringe',
            'nl' => 'Thüringen',
            'de' => 'Thüringen',
            'es' => 'Turingia',
        ],
        'luxembourg' => [
            'en' => 'Luxembourg',
            'fr' => 'Luxembourg',
            'nl' => 'Luxemburg',
            'de' => 'Luxemburg',
            'es' => 'Luxemburgo',
        ],
        'auvergne-rhone-alpes' => [
            'en' => 'Auvergne-Rhône-Alpes',
            'fr' => 'Auvergne-Rhône-Alpes',
            'nl' => 'Auvergne-Rhône-Alpes',
            'de' => 'Auvergne-Rhône-Alpes',
            'es' => 'Auvernia-Ródano-Alpes',
        ],
        'bourgogne-franche-comte' => [
            'en' => 'Burgundy-Franche-Comté',
            'fr' => 'Bourgogne-Franche-Comté',
            'nl' => 'Bourgondië-Franche-Comté',
            'de' => 'Burgund-Franche-Comté',
            'es' => 'Borgoña-Franco Condado',
        ],
        'bretagne' => [
            'en' => 'Brittany',
            'fr' => 'Bretagne',
            'nl' => 'Bretagne',
            'de' => 'Bretagne',
            'es' => 'Bretaña',
        ],
        'centre-val-de-loire' => [
            'en' => 'Centre-Val de Loire',
            'fr' => 'Centre-Val de Loire',
            'nl' => 'Centre-Val de Loire',
            'de' => 'Centre-Val de Loire',
            'es' => 'Centro-Valle del Loira',
        ],
        'corse' => [
            'en' => 'Corsica',
            'fr' => 'Corse',
            'nl' => 'Corsica',
            'de' => 'Korsika',
            'es' => 'Córcega',
        ],
        'grand-est' => [
            'en' => 'Grand Est',
            'fr' => 'Grand Est',
            'nl' => 'Grand Est',
            'de' => 'Grand Est',
            'es' => 'Gran Este',
        ],
        'hauts-de-france' => [
            'en' => 'Hauts-de-France',
            'fr' => 'Hauts-de-France',
            'nl' => 'Hauts-de-France',
            'de' => 'Hauts-de-France',
            'es' => 'Alta Francia',
        ],
        'ile-de-france' => [
            'en' => 'Île-de-France',
            'fr' => 'Île-de-France',
            'nl' => 'Île-de-France',
            'de' => 'Île-de-France',
            'es' => 'Isla de Francia',
        ],
        'nouvelle-aquitaine' => [
            'en' => 'Nouvelle-Aquitaine',
            'fr' => 'Nouvelle-Aquitaine',
            'nl' => 'Nieuw-Aquitanië',
            'de' => 'Nouvelle-Aquitaine',
            'es' => 'Nueva Aquitania',
        ],
        'normandie' => [
            'en' => 'Normandy',
            'fr' => 'Normandie',
            'nl' => 'Normandië',
            'de' => 'Normandie',
            'es' => 'Normandía',
        ],
        'occitanie' => [
            'en' => 'Occitania',
            'fr' => 'Occitanie',
            'nl' => 'Occitanië',
            'de' => 'Okzitanien',
            'es' => 'Occitania',
        ],
        'provence-alpes-cote-d-azur' => [
            'en' => 'Provence-Alpes-Côte d\'Azur',
            'fr' => 'Provence-Alpes-Côte d\'Azur',
            'nl' => 'Provence-Alpes-Côte d\'Azur',
            'de' => 'Provence-Alpes-Côte d\'Azur',
            'es' => 'Provenza-Alpes-Costa Azul',
        ],
        'pays-de-la-loire' => [
            'en' => 'Pays de la Loire',
            'fr' => 'Pays de la Loire',
            'nl' => 'Pays de la Loire',
            'de' => 'Pays de la Loire',
            'es' => 'País del Loira',
        ],
        'aargau' => [
            'en' => 'Aargau',
            'fr' => 'Argovie',
            'nl' => 'Aargau',
            'de' => 'Aargau',
            'es' => 'Argovia',
        ],
        'appenzell-innerrhoden' => [
            'en' => 'Appenzell Innerrhoden',
            'fr' => 'Appenzell Rhodes-Intérieures',
            'nl' => 'Appenzell Innerrhoden',
            'de' => 'Appenzell Innerrhoden',
            'es' => 'Appenzell Rodas Interiores',
        ],
        'appenzell-ausserrhoden' => [
            'en' => 'Appenzell Ausserrhoden',
            'fr' => 'Appenzell Rhodes-Extérieures',
            'nl' => 'Appenzell Ausserrhoden',
            'de' => 'Appenzell Ausserrhoden',
            'es' => 'Appenzell Rodas Exteriores',
        ],
        'bern' => [
            'en' => 'Bern',
            'fr' => 'Berne',
            'nl' => 'Bern',
            'de' => 'Bern',
            'es' => 'Berna',
        ],
        'basel-landschaft' => [
            'en' => 'Basel-Landschaft',
            'fr' => 'Bâle-Campagne',
            'nl' => 'Basel-Landschaft',
            'de' => 'Basel-Landschaft',
            'es' => 'Basilea-Campiña',
        ],
        'basel-stadt' => [
            'en' => 'Basel-Stadt',
            'fr' => 'Bâle-Ville',
            'nl' => 'Basel-Stad',
            'de' => 'Basel-Stadt',
            'es' => 'Basilea-Ciudad',
        ],
        'fribourg' => [
            'en' => 'Fribourg',
            'fr' => 'Fribourg',
            'nl' => 'Fribourg',
            'de' => 'Freiburg',
            'es' => 'Friburgo',
        ],
        'geneve' => [
            'en' => 'Geneva',
            'fr' => 'Genève',
            'nl' => 'Genève',
            'de' => 'Genf',
            'es' => 'Ginebra',
        ],
        'glarus' => [
            'en' => 'Glarus',
            'fr' => 'Glaris',
            'nl' => 'Glarus',
            'de' => 'Glarus',
            'es' => 'Glaris',
        ],
        'graubunden' => [
            'en' => 'Grisons',
            'fr' => 'Grisons',
            'nl' => 'Graubünden',
            'de' => 'Graubünden',
            'es' => 'Grisones',
        ],
        'jura' => [
            'en' => 'Jura',
            'fr' => 'Jura',
            'nl' => 'Jura',
            'de' => 'Jura',
            'es' => 'Jura',
        ],
        'luzern' => [
            'en' => 'Lucerne',
            'fr' => 'Lucerne',
            'nl' => 'Luzern',
            'de' => 'Luzern',
            'es' => 'Lucerna',
        ],
        'neuchatel' => [
            'en' => 'Neuchâtel',
            'fr' => 'Neuchâtel',
            'nl' => 'Neuchâtel',
            'de' => 'Neuenburg',
            'es' => 'Neuchâtel',
        ],
        'nidwalden' => [
            'en' => 'Nidwalden',
            'fr' => 'Nidwald',
            'nl' => 'Nidwalden',
            'de' => 'Nidwalden',
            'es' => 'Nidwalden',
        ],
        'obwalden' => [
            'en' => 'Obwalden',
            'fr' => 'Obwald',
            'nl' => 'Obwalden',
            'de' => 'Obwalden',
            'es' => 'Obwalden',
        ],
        'st-gallen' => [
            'en' => 'St. Gallen',
            'fr' => 'Saint-Gall',
            'nl' => 'Sankt Gallen',
            'de' => 'St. Gallen',
            'es' => 'San Galo',
        ],
        'schaffhausen' => [
            'en' => 'Schaffhausen',
            'fr' => 'Schaffhouse',
            'nl' => 'Schaffhausen',
            'de' => 'Schaffhausen',
            'es' => 'Schaffhausen',
        ],
        'solothurn' => [
            'en' => 'Solothurn',
            'fr' => 'Soleure',
            'nl' => 'Solothurn',
            'de' => 'Solothurn',
            'es' => 'Soleura',
        ],
        'schwyz' => [
            'en' => 'Schwyz',
            'fr' => 'Schwytz',
            'nl' => 'Schwyz',
            'de' => 'Schwyz',
            'es' => 'Schwyz',
        ],
        'thurgau' => [
            'en' => 'Thurgau',
            'fr' => 'Thurgovie',
            'nl' => 'Thurgau',
            'de' => 'Thurgau',
            'es' => 'Turgovia',
        ],
        'ticino' => [
            'en' => 'Ticino',
            'fr' => 'Tessin',
            'nl' => 'Ticino',
            'de' => 'Tessin',
            'es' => 'Tesino',
        ],
        'uri' => [
            'en' => 'Uri',
            'fr' => 'Uri',
            'nl' => 'Uri',
            'de' => 'Uri',
            'es' => 'Uri',
        ],
        'vaud' => [
            'en' => 'Vaud',
            'fr' => 'Vaud',
            'nl' => 'Vaud',
            'de' => 'Waadt',
            'es' => 'Vaud',
        ],
        'valais' => [
            'en' => 'Valais',
            'fr' => 'Valais',
            'nl' => 'Wallis',
            'de' => 'Wallis',
            'es' => 'Valais',
        ],
        'zug' => [
            'en' => 'Zug',
            'fr' => 'Zoug',
            'nl' => 'Zug',
            'de' => 'Zug',
            'es' => 'Zug',
        ],
        'zurich' => [
            'en' => 'Zurich',
            'fr' => 'Zurich',
            'nl' => 'Zürich',
            'de' => 'Zürich',
            'es' => 'Zúrich',
        ],
        'england' => [
            'en' => 'England',
            'fr' => 'Angleterre',
            'nl' => 'Engeland',
            'de' => 'England',
            'es' => 'Inglaterra',
        ],
        'scotland' => [
            'en' => 'Scotland',
            'fr' => 'Écosse',
            'nl' => 'Schotland',
            'de' => 'Schottland',
            'es' => 'Escocia',
        ],
        'wales' => [
            'en' => 'Wales',
            'fr' => 'Pays de Galles',
            'nl' => 'Wales',
            'de' => 'Wales',
            'es' => 'Gales',
        ],
        'northern-ireland' => [
            'en' => 'Northern Ireland',
            'fr' => 'Irlande du Nord',
            'nl' => 'Noord-Ierland',
            'de' => 'Nordirland',
            'es' => 'Irlanda del Norte',
        ],
        'piemonte' => [
            'en' => 'Piedmont',
            'fr' => 'Piémont',
            'nl' => 'Piëmont',
            'de' => 'Piemont',
            'es' => 'Piamonte',
        ],
        'valle-d-aosta' => [
            'en' => 'Aosta Valley',
            'fr' => 'Vallée d\'Aoste',
            'nl' => 'Valle d\'Aosta',
            'de' => 'Aostatal',
            'es' => 'Valle de Aosta',
        ],
        'lombardia' => [
            'en' => 'Lombardy',
            'fr' => 'Lombardie',
            'nl' => 'Lombardije',
            'de' => 'Lombardei',
            'es' => 'Lombardía',
        ],
        'trentino-alto-adige' => [
            'en' => 'Trentino-South Tyrol',
            'fr' => 'Trentin-Haut-Adige',
            'nl' => 'Trentino-Zuid-Tirol',
            'de' => 'Trentino-Südtirol',
            'es' => 'Trentino-Alto Adigio',
        ],
        'veneto' => [
            'en' => 'Veneto',
            'fr' => 'Vénétie',
            'nl' => 'Veneto',
            'de' => 'Venetien',
            'es' => 'Véneto',
        ],
        'friuli-venezia-giulia' => [
            'en' => 'Friuli-Venezia Giulia',
            'fr' => 'Frioul-Vénétie Julienne',
            'nl' => 'Friuli-Venezia Giulia',
            'de' => 'Friaul-Julisch Venetien',
            'es' => 'Friuli-Venecia Julia',
        ],
        'liguria' => [
            'en' => 'Liguria',
            'fr' => 'Ligurie',
            'nl' => 'Ligurië',
            'de' => 'Ligurien',
            'es' => 'Liguria',
        ],
        'emilia-romagna' => [
            'en' => 'Emilia-Romagna',
            'fr' => 'Émilie-Romagne',
            'nl' => 'Emilia-Romagna',
            'de' => 'Emilia-Romagna',
            'es' => 'Emilia-Romaña',
        ],
        'toscana' => [
            'en' => 'Tuscany',
            'fr' => 'Toscane',
            'nl' => 'Toscane',
            'de' => 'Toskana',
            'es' => 'Toscana',
        ],
        'umbria' => [
            'en' => 'Umbria',
            'fr' => 'Ombrie',
            'nl' => 'Umbrië',
            'de' => 'Umbrien',
            'es' => 'Umbría',
        ],
        'marche' => [
            'en' => 'Marche',
            'fr' => 'Marches',
            'nl' => 'Marche',
            'de' => 'Marken',
            'es' => 'Marcas',
        ],
        'lazio' => [
            'en' => 'Lazio',
            'fr' => 'Latium',
            'nl' => 'Lazio',
            'de' => 'Latium',
            'es' => 'Lacio',
        ],
        'abruzzo' => [
            'en' => 'Abruzzo',
            'fr' => 'Abruzzes',
            'nl' => 'Abruzzen',
            'de' => 'Abruzzen',
            'es' => 'Abruzos',
        ],
        'molise' => [
            'en' => 'Molise',
            'fr' => 'Molise',
            'nl' => 'Molise',
            'de' => 'Molise',
            'es' => 'Molise',
        ],
        'campania' => [
            'en' => 'Campania',
            'fr' => 'Campanie',
            'nl' => 'Campanië',
            'de' => 'Kampanien',
            'es' => 'Campania',
        ],
        'puglia' => [
            'en' => 'Apulia',
            'fr' => 'Pouilles',
            'nl' => 'Apulië',
            'de' => 'Apulien',
            'es' => 'Apulia',
        ],
        'basilicata' => [
            'en' => 'Basilicata',
            'fr' => 'Basilicate',
            'nl' => 'Basilicata',
            'de' => 'Basilikata',
            'es' => 'Basilicata',
        ],
        'calabria' => [
            'en' => 'Calabria',
            'fr' => 'Calabre',
            'nl' => 'Calabrië',
            'de' => 'Kalabrien',
            'es' => 'Calabria',
        ],
        'sicilia' => [
            'en' => 'Sicily',
            'fr' => 'Sicile',
            'nl' => 'Sicilië',
            'de' => 'Sizilien',
            'es' => 'Sicilia',
        ],
        'sardegna' => [
            'en' => 'Sardinia',
            'fr' => 'Sardaigne',
            'nl' => 'Sardinië',
            'de' => 'Sardinien',
            'es' => 'Cerdeña',
        ],
        'australian-capital-territory' => [
            'en' => 'Australian Capital Territory',
            'fr' => 'Territoire de la capitale australienne',
            'nl' => 'Australisch Hoofdstedelijk Territorium',
            'de' => 'Australisches Hauptstadtterritorium',
            'es' => 'Territorio de la Capital Australiana',
        ],
        'new-south-wales' => [
            'en' => 'New South Wales',
            'fr' => 'Nouvelle-Galles du Sud',
            'nl' => 'Nieuw-Zuid-Wales',
            'de' => 'Neusüdwales',
            'es' => 'Nueva Gales del Sur',
        ],
        'northern-territory' => [
            'en' => 'Northern Territory',
            'fr' => 'Territoire du Nord',
            'nl' => 'Noordelijk Territorium',
            'de' => 'Northern Territory',
            'es' => 'Territorio del Norte',
        ],
        'queensland' => [
            'en' => 'Queensland',
            'fr' => 'Queensland',
            'nl' => 'Queensland',
            'de' => 'Queensland',
            'es' => 'Queensland',
        ],
        'south-australia' => [
            'en' => 'South Australia',
            'fr' => 'Australie-Méridionale',
            'nl' => 'Zuid-Australië',
            'de' => 'South Australia',
            'es' => 'Australia Meridional',
        ],
        'tasmania' => [
            'en' => 'Tasmania',
            'fr' => 'Tasmanie',
            'nl' => 'Tasmanië',
            'de' => 'Tasmanien',
            'es' => 'Tasmania',
        ],
        'victoria' => [
            'en' => 'Victoria',
            'fr' => 'Victoria',
            'nl' => 'Victoria',
            'de' => 'Victoria',
            'es' => 'Victoria',
        ],
        'western-australia' => [
            'en' => 'Western Australia',
            'fr' => 'Australie-Occidentale',
            'nl' => 'West-Australië',
            'de' => 'Western Australia',
            'es' => 'Australia Occidental',
        ],
        'hokkaido' => [
            'en' => 'Hokkaido',
            'fr' => 'Hokkaido',
            'nl' => 'Hokkaido',
            'de' => 'Hokkaido',
            'es' => 'Hokkaido',
        ],
        'aomori' => [
            'en' => 'Aomori',
            'fr' => 'Aomori',
            'nl' => 'Aomori',
            'de' => 'Aomori',
            'es' => 'Aomori',
        ],
        'iwate' => [
            'en' => 'Iwate',
            'fr' => 'Iwate',
            'nl' => 'Iwate',
            'de' => 'Iwate',
            'es' => 'Iwate',
        ],
        'miyagi' => [
            'en' => 'Miyagi',
            'fr' => 'Miyagi',
            'nl' => 'Miyagi',
            'de' => 'Miyagi',
            'es' => 'Miyagi',
        ],
        'akita' => [
            'en' => 'Akita',
            'fr' => 'Akita',
            'nl' => 'Akita',
            'de' => 'Akita',
            'es' => 'Akita',
        ],
        'yamagata' => [
            'en' => 'Yamagata',
            'fr' => 'Yamagata',
            'nl' => 'Yamagata',
            'de' => 'Yamagata',
            'es' => 'Yamagata',
        ],
        'fukushima' => [
            'en' => 'Fukushima',
            'fr' => 'Fukushima',
            'nl' => 'Fukushima',
            'de' => 'Fukushima',
            'es' => 'Fukushima',
        ],
        'ibaraki' => [
            'en' => 'Ibaraki',
            'fr' => 'Ibaraki',
            'nl' => 'Ibaraki',
            'de' => 'Ibaraki',
            'es' => 'Ibaraki',
        ],
        'tochigi' => [
            'en' => 'Tochigi',
            'fr' => 'Tochigi',
            'nl' => 'Tochigi',
            'de' => 'Tochigi',
            'es' => 'Tochigi',
        ],
        'gunma' => [
            'en' => 'Gunma',
            'fr' => 'Gunma',
            'nl' => 'Gunma',
            'de' => 'Gunma',
            'es' => 'Gunma',
        ],
        'saitama' => [
            'en' => 'Saitama',
            'fr' => 'Saitama',
            'nl' => 'Saitama',
            'de' => 'Saitama',
            'es' => 'Saitama',
        ],
        'chiba' => [
            'en' => 'Chiba',
            'fr' => 'Chiba',
            'nl' => 'Chiba',
            'de' => 'Chiba',
            'es' => 'Chiba',
        ],
        'tokyo' => [
            'en' => 'Tokyo',
            'fr' => 'Tokyo',
            'nl' => 'Tokio',
            'de' => 'Tokio',
            'es' => 'Tokio',
        ],
        'kanagawa' => [
            'en' => 'Kanagawa',
            'fr' => 'Kanagawa',
            'nl' => 'Kanagawa',
            'de' => 'Kanagawa',
            'es' => 'Kanagawa',
        ],
        'niigata' => [
            'en' => 'Niigata',
            'fr' => 'Niigata',
            'nl' => 'Niigata',
            'de' => 'Niigata',
            'es' => 'Niigata',
        ],
        'toyama' => [
            'en' => 'Toyama',
            'fr' => 'Toyama',
            'nl' => 'Toyama',
            'de' => 'Toyama',
            'es' => 'Toyama',
        ],
        'ishikawa' => [
            'en' => 'Ishikawa',
            'fr' => 'Ishikawa',
            'nl' => 'Ishikawa',
            'de' => 'Ishikawa',
            'es' => 'Ishikawa',
        ],
        'fukui' => [
            'en' => 'Fukui',
            'fr' => 'Fukui',
            'nl' => 'Fukui',
            'de' => 'Fukui',
            'es' => 'Fukui',
        ],
        'yamanashi' => [
            'en' => 'Yamanashi',
            'fr' => 'Yamanashi',
            'nl' => 'Yamanashi',
            'de' => 'Yamanashi',
            'es' => 'Yamanashi',
        ],
        'nagano' => [
            'en' => 'Nagano',
            'fr' => 'Nagano',
            'nl' => 'Nagano',
            'de' => 'Nagano',
            'es' => 'Nagano',
        ],
        'gifu' => [
            'en' => 'Gifu',
            'fr' => 'Gifu',
            'nl' => 'Gifu',
            'de' => 'Gifu',
            'es' => 'Gifu',
        ],
        'shizuoka' => [
            'en' => 'Shizuoka',
            'fr' => 'Shizuoka',
            'nl' => 'Shizuoka',
            'de' => 'Shizuoka',
            'es' => 'Shizuoka',
        ],
        'aichi' => [
            'en' => 'Aichi',
            'fr' => 'Aichi',
            'nl' => 'Aichi',
            'de' => 'Aichi',
            'es' => 'Aichi',
        ],
        'mie' => [
            'en' => 'Mie',
            'fr' => 'Mie',
            'nl' => 'Mie',
            'de' => 'Mie',
            'es' => 'Mie',
        ],
        'shiga' => [
            'en' => 'Shiga',
            'fr' => 'Shiga',
            'nl' => 'Shiga',
            'de' => 'Shiga',
            'es' => 'Shiga',
        ],
        'kyoto' => [
            'en' => 'Kyoto',
            'fr' => 'Kyoto',
            'nl' => 'Kyoto',
            'de' => 'Kyoto',
            'es' => 'Kioto',
        ],
        'osaka' => [
            'en' => 'Osaka',
            'fr' => 'Osaka',
            'nl' => 'Osaka',
            'de' => 'Osaka',
            'es' => 'Osaka',
        ],
        'hyogo' => [
            'en' => 'Hyogo',
            'fr' => 'Hyogo',
            'nl' => 'Hyogo',
            'de' => 'Hyogo',
            'es' => 'Hyogo',
        ],
        'nara' => [
            'en' => 'Nara',
            'fr' => 'Nara',
            'nl' => 'Nara',
            'de' => 'Nara',
            'es' => 'Nara',
        ],
        'wakayama' => [
            'en' => 'Wakayama',
            'fr' => 'Wakayama',
            'nl' => 'Wakayama',
            'de' => 'Wakayama',
            'es' => 'Wakayama',
        ],
        'tottori' => [
            'en' => 'Tottori',
            'fr' => 'Tottori',
            'nl' => 'Tottori',
            'de' => 'Tottori',
            'es' => 'Tottori',
        ],
        'shimane' => [
            'en' => 'Shimane',
            'fr' => 'Shimane',
            'nl' => 'Shimane',
            'de' => 'Shimane',
            'es' => 'Shimane',
        ],
        'okayama' => [
            'en' => 'Okayama',
            'fr' => 'Okayama',
            'nl' => 'Okayama',
            'de' => 'Okayama',
            'es' => 'Okayama',
        ],
        'hiroshima' => [
            'en' => 'Hiroshima',
            'fr' => 'Hiroshima',
            'nl' => 'Hiroshima',
            'de' => 'Hiroshima',
            'es' => 'Hiroshima',
        ],
        'yamaguchi' => [
            'en' => 'Yamaguchi',
            'fr' => 'Yamaguchi',
            'nl' => 'Yamaguchi',
            'de' => 'Yamaguchi',
            'es' => 'Yamaguchi',
        ],
        'tokushima' => [
            'en' => 'Tokushima',
            'fr' => 'Tokushima',
            'nl' => 'Tokushima',
            'de' => 'Tokushima',
            'es' => 'Tokushima',
        ],
        'kagawa' => [
            'en' => 'Kagawa',
            'fr' => 'Kagawa',
            'nl' => 'Kagawa',
            'de' => 'Kagawa',
            'es' => 'Kagawa',
        ],
        'ehime' => [
            'en' => 'Ehime',
            'fr' => 'Ehime',
            'nl' => 'Ehime',
            'de' => 'Ehime',
            'es' => 'Ehime',
        ],
        'kochi' => [
            'en' => 'Kochi',
            'fr' => 'Kochi',
            'nl' => 'Kochi',
            'de' => 'Kochi',
            'es' => 'Kochi',
        ],
        'fukuoka' => [
            'en' => 'Fukuoka',
            'fr' => 'Fukuoka',
            'nl' => 'Fukuoka',
            'de' => 'Fukuoka',
            'es' => 'Fukuoka',
        ],
        'saga' => [
            'en' => 'Saga',
            'fr' => 'Saga',
            'nl' => 'Saga',
            'de' => 'Saga',
            'es' => 'Saga',
        ],
        'nagasaki' => [
            'en' => 'Nagasaki',
            'fr' => 'Nagasaki',
            'nl' => 'Nagasaki',
            'de' => 'Nagasaki',
            'es' => 'Nagasaki',
        ],
        'kumamoto' => [
            'en' => 'Kumamoto',
            'fr' => 'Kumamoto',
            'nl' => 'Kumamoto',
            'de' => 'Kumamoto',
            'es' => 'Kumamoto',
        ],
        'oita' => [
            'en' => 'Oita',
            'fr' => 'Oita',
            'nl' => 'Oita',
            'de' => 'Oita',
            'es' => 'Oita',
        ],
        'miyazaki' => [
            'en' => 'Miyazaki',
            'fr' => 'Miyazaki',
            'nl' => 'Miyazaki',
            'de' => 'Miyazaki',
            'es' => 'Miyazaki',
        ],
        'kagoshima' => [
            'en' => 'Kagoshima',
            'fr' => 'Kagoshima',
            'nl' => 'Kagoshima',
            'de' => 'Kagoshima',
            'es' => 'Kagoshima',
        ],
        'okinawa' => [
            'en' => 'Okinawa',
            'fr' => 'Okinawa',
            'nl' => 'Okinawa',
            'de' => 'Okinawa',
            'es' => 'Okinawa',
        ],
        'california' => [
            'en' => 'California',
            'fr' => 'Californie',
            'nl' => 'Californië',
            'de' => 'Kalifornien',
            'es' => 'California',
        ],
        'colorado' => [
            'en' => 'Colorado',
            'fr' => 'Colorado',
            'nl' => 'Colorado',
            'de' => 'Colorado',
            'es' => 'Colorado',
        ],
        'andalucia' => [
            'en' => 'Andalusia',
            'fr' => 'Andalousie',
            'nl' => 'Andalusië',
            'de' => 'Andalusien',
            'es' => 'Andalucía',
        ],
        'aragon' => [
            'en' => 'Aragon',
            'fr' => 'Aragon',
            'nl' => 'Aragón',
            'de' => 'Aragonien',
            'es' => 'Aragón',
        ],
        'asturias' => [
            'en' => 'Asturias',
            'fr' => 'Asturies',
            'nl' => 'Asturië',
            'de' => 'Asturien',
            'es' => 'Asturias',
        ],
        'cantabria' => [
            'en' => 'Cantabria',
            'fr' => 'Cantabrie',
            'nl' => 'Cantabrië',
            'de' => 'Kantabrien',
            'es' => 'Cantabria',
        ],
        'ceuta' => [
            'en' => 'Ceuta',
            'fr' => 'Ceuta',
            'nl' => 'Ceuta',
            'de' => 'Ceuta',
            'es' => 'Ceuta',
        ],
        'castilla-y-leon' => [
            'en' => 'Castile and León',
            'fr' => 'Castille-et-León',
            'nl' => 'Castilië en León',
            'de' => 'Kastilien und León',
            'es' => 'Castilla y León',
        ],
        'castilla-la-mancha' => [
            'en' => 'Castilla-La Mancha',
            'fr' => 'Castille-La Manche',
            'nl' => 'Castilla-La Mancha',
            'de' => 'Kastilien-La Mancha',
            'es' => 'Castilla-La Mancha',
        ],
        'canarias' => [
            'en' => 'Canary Islands',
            'fr' => 'Îles Canaries',
            'nl' => 'Canarische Eilanden',
            'de' => 'Kanarische Inseln',
            'es' => 'Canarias',
        ],
        'catalunya' => [
            'en' => 'Catalonia',
            'fr' => 'Catalogne',
            'nl' => 'Catalonië',
            'de' => 'Katalonien',
            'es' => 'Cataluña',
        ],
        'extremadura' => [
            'en' => 'Extremadura',
            'fr' => 'Estrémadure',
            'nl' => 'Extremadura',
            'de' => 'Extremadura',
            'es' => 'Extremadura',
        ],
        'galicia' => [
            'en' => 'Galicia',
            'fr' => 'Galice',
            'nl' => 'Galicië',
            'de' => 'Galicien',
            'es' => 'Galicia',
        ],
        'illes-balears' => [
            'en' => 'Balearic Islands',
            'fr' => 'Îles Baléares',
            'nl' => 'Balearen',
            'de' => 'Balearen',
            'es' => 'Islas Baleares',
        ],
        'murcia' => [
            'en' => 'Region of Murcia',
            'fr' => 'Région de Murcie',
            'nl' => 'Regio Murcia',
            'de' => 'Region Murcia',
            'es' => 'Región de Murcia',
        ],
        'madrid' => [
            'en' => 'Community of Madrid',
            'fr' => 'Communauté de Madrid',
            'nl' => 'Gemeenschap Madrid',
            'de' => 'Autonome Gemeinschaft Madrid',
            'es' => 'Comunidad de Madrid',
        ],
        'melilla' => [
            'en' => 'Melilla',
            'fr' => 'Melilla',
            'nl' => 'Melilla',
            'de' => 'Melilla',
            'es' => 'Melilla',
        ],
        'navarra' => [
            'en' => 'Navarre',
            'fr' => 'Navarre',
            'nl' => 'Navarra',
            'de' => 'Navarra',
            'es' => 'Navarra',
        ],
        'pais-vasco' => [
            'en' => 'Basque Country',
            'fr' => 'Pays basque',
            'nl' => 'Baskenland',
            'de' => 'Baskenland',
            'es' => 'País Vasco',
        ],
        'la-rioja-es' => [
            'en' => 'La Rioja',
            'fr' => 'La Rioja',
            'nl' => 'La Rioja',
            'de' => 'La Rioja',
            'es' => 'La Rioja',
        ],
        'comunitat-valenciana' => [
            'en' => 'Valencian Community',
            'fr' => 'Communauté valencienne',
            'nl' => 'Valenciaanse Gemeenschap',
            'de' => 'Valencianische Gemeinschaft',
            'es' => 'Comunidad Valenciana',
        ],
        'slovenia' => [
            'en' => 'Slovenia',
            'fr' => 'Slovénie',
            'nl' => 'Slovenië',
            'de' => 'Slowenien',
            'es' => 'Eslovenia',
        ],
        'kigali' => [
            'en' => 'City of Kigali',
            'fr' => 'Ville de Kigali',
            'nl' => 'Stad Kigali',
            'de' => 'Stadt Kigali',
            'es' => 'Ciudad de Kigali',
        ],
        'iburasirazuba' => [
            'en' => 'Eastern Province',
            'fr' => 'Province de l\'Est',
            'nl' => 'Oostelijke Provincie',
            'de' => 'Ostprovinz',
            'es' => 'Provincia del Este',
        ],
        'amajyaruguru' => [
            'en' => 'Northern Province',
            'fr' => 'Province du Nord',
            'nl' => 'Noordelijke Provincie',
            'de' => 'Nordprovinz',
            'es' => 'Provincia del Norte',
        ],
        'iburengerazuba' => [
            'en' => 'Western Province',
            'fr' => 'Province de l\'Ouest',
            'nl' => 'Westelijke Provincie',
            'de' => 'Westprovinz',
            'es' => 'Provincia del Oeste',
        ],
        'amajyepfo' => [
            'en' => 'Southern Province',
            'fr' => 'Province du Sud',
            'nl' => 'Zuidelijke Provincie',
            'de' => 'Südprovinz',
            'es' => 'Provincia del Sur',
        ],
        'eastern-cape' => [
            'en' => 'Eastern Cape',
            'fr' => 'Cap-Oriental',
            'nl' => 'Oost-Kaap',
            'de' => 'Ostkap',
            'es' => 'Cabo Oriental',
        ],
        'free-state' => [
            'en' => 'Free State',
            'fr' => 'État-Libre',
            'nl' => 'Vrijstaat',
            'de' => 'Freistaat',
            'es' => 'Estado Libre',
        ],
        'gauteng' => [
            'en' => 'Gauteng',
            'fr' => 'Gauteng',
            'nl' => 'Gauteng',
            'de' => 'Gauteng',
            'es' => 'Gauteng',
        ],
        'kwazulu-natal' => [
            'en' => 'KwaZulu-Natal',
            'fr' => 'KwaZulu-Natal',
            'nl' => 'KwaZulu-Natal',
            'de' => 'KwaZulu-Natal',
            'es' => 'KwaZulu-Natal',
        ],
        'limpopo' => [
            'en' => 'Limpopo',
            'fr' => 'Limpopo',
            'nl' => 'Limpopo',
            'de' => 'Limpopo',
            'es' => 'Limpopo',
        ],
        'mpumalanga' => [
            'en' => 'Mpumalanga',
            'fr' => 'Mpumalanga',
            'nl' => 'Mpumalanga',
            'de' => 'Mpumalanga',
            'es' => 'Mpumalanga',
        ],
        'northern-cape' => [
            'en' => 'Northern Cape',
            'fr' => 'Cap-Nord',
            'nl' => 'Noord-Kaap',
            'de' => 'Nordkap',
            'es' => 'Cabo Norte',
        ],
        'north-west' => [
            'en' => 'North West',
            'fr' => 'Nord-Ouest',
            'nl' => 'Noordwest',
            'de' => 'Nordwest',
            'es' => 'Noroeste',
        ],
        'western-cape' => [
            'en' => 'Western Cape',
            'fr' => 'Cap-Occidental',
            'nl' => 'West-Kaap',
            'de' => 'Westkap',
            'es' => 'Cabo Occidental',
        ],
        'amazonas-co' => [
            'en' => 'Amazonas',
            'fr' => 'Amazonas',
            'nl' => 'Amazonas',
            'de' => 'Amazonas',
            'es' => 'Amazonas',
        ],
        'antioquia' => [
            'en' => 'Antioquia',
            'fr' => 'Antioquia',
            'nl' => 'Antioquia',
            'de' => 'Antioquia',
            'es' => 'Antioquia',
        ],
        'arauca' => [
            'en' => 'Arauca',
            'fr' => 'Arauca',
            'nl' => 'Arauca',
            'de' => 'Arauca',
            'es' => 'Arauca',
        ],
        'atlantico' => [
            'en' => 'Atlántico',
            'fr' => 'Atlántico',
            'nl' => 'Atlántico',
            'de' => 'Atlántico',
            'es' => 'Atlántico',
        ],
        'bolivar-co' => [
            'en' => 'Bolívar',
            'fr' => 'Bolívar',
            'nl' => 'Bolívar',
            'de' => 'Bolívar',
            'es' => 'Bolívar',
        ],
        'boyaca' => [
            'en' => 'Boyacá',
            'fr' => 'Boyacá',
            'nl' => 'Boyacá',
            'de' => 'Boyacá',
            'es' => 'Boyacá',
        ],
        'caldas' => [
            'en' => 'Caldas',
            'fr' => 'Caldas',
            'nl' => 'Caldas',
            'de' => 'Caldas',
            'es' => 'Caldas',
        ],
        'caqueta' => [
            'en' => 'Caquetá',
            'fr' => 'Caquetá',
            'nl' => 'Caquetá',
            'de' => 'Caquetá',
            'es' => 'Caquetá',
        ],
        'casanare' => [
            'en' => 'Casanare',
            'fr' => 'Casanare',
            'nl' => 'Casanare',
            'de' => 'Casanare',
            'es' => 'Casanare',
        ],
        'cauca' => [
            'en' => 'Cauca',
            'fr' => 'Cauca',
            'nl' => 'Cauca',
            'de' => 'Cauca',
            'es' => 'Cauca',
        ],
        'cesar' => [
            'en' => 'Cesar',
            'fr' => 'Cesar',
            'nl' => 'Cesar',
            'de' => 'Cesar',
            'es' => 'Cesar',
        ],
        'choco' => [
            'en' => 'Chocó',
            'fr' => 'Chocó',
            'nl' => 'Chocó',
            'de' => 'Chocó',
            'es' => 'Chocó',
        ],
        'cordoba-co' => [
            'en' => 'Córdoba',
            'fr' => 'Córdoba',
            'nl' => 'Córdoba',
            'de' => 'Córdoba',
            'es' => 'Córdoba',
        ],
        'cundinamarca' => [
            'en' => 'Cundinamarca',
            'fr' => 'Cundinamarca',
            'nl' => 'Cundinamarca',
            'de' => 'Cundinamarca',
            'es' => 'Cundinamarca',
        ],
        'bogota' => [
            'en' => 'Bogotá',
            'fr' => 'Bogotá',
            'nl' => 'Bogotá',
            'de' => 'Bogotá',
            'es' => 'Bogotá',
        ],
        'guainia' => [
            'en' => 'Guainía',
            'fr' => 'Guainía',
            'nl' => 'Guainía',
            'de' => 'Guainía',
            'es' => 'Guainía',
        ],
        'guaviare' => [
            'en' => 'Guaviare',
            'fr' => 'Guaviare',
            'nl' => 'Guaviare',
            'de' => 'Guaviare',
            'es' => 'Guaviare',
        ],
        'huila' => [
            'en' => 'Huila',
            'fr' => 'Huila',
            'nl' => 'Huila',
            'de' => 'Huila',
            'es' => 'Huila',
        ],
        'la-guajira' => [
            'en' => 'La Guajira',
            'fr' => 'La Guajira',
            'nl' => 'La Guajira',
            'de' => 'La Guajira',
            'es' => 'La Guajira',
        ],
        'magdalena' => [
            'en' => 'Magdalena',
            'fr' => 'Magdalena',
            'nl' => 'Magdalena',
            'de' => 'Magdalena',
            'es' => 'Magdalena',
        ],
        'meta' => [
            'en' => 'Meta',
            'fr' => 'Meta',
            'nl' => 'Meta',
            'de' => 'Meta',
            'es' => 'Meta',
        ],
        'narino' => [
            'en' => 'Nariño',
            'fr' => 'Nariño',
            'nl' => 'Nariño',
            'de' => 'Nariño',
            'es' => 'Nariño',
        ],
        'norte-de-santander' => [
            'en' => 'Norte de Santander',
            'fr' => 'Norte de Santander',
            'nl' => 'Norte de Santander',
            'de' => 'Norte de Santander',
            'es' => 'Norte de Santander',
        ],
        'putumayo' => [
            'en' => 'Putumayo',
            'fr' => 'Putumayo',
            'nl' => 'Putumayo',
            'de' => 'Putumayo',
            'es' => 'Putumayo',
        ],
        'quindio' => [
            'en' => 'Quindío',
            'fr' => 'Quindío',
            'nl' => 'Quindío',
            'de' => 'Quindío',
            'es' => 'Quindío',
        ],
        'risaralda' => [
            'en' => 'Risaralda',
            'fr' => 'Risaralda',
            'nl' => 'Risaralda',
            'de' => 'Risaralda',
            'es' => 'Risaralda',
        ],
        'santander' => [
            'en' => 'Santander',
            'fr' => 'Santander',
            'nl' => 'Santander',
            'de' => 'Santander',
            'es' => 'Santander',
        ],
        'san-andres-y-providencia' => [
            'en' => 'San Andrés y Providencia',
            'fr' => 'San Andrés y Providencia',
            'nl' => 'San Andrés y Providencia',
            'de' => 'San Andrés y Providencia',
            'es' => 'San Andrés y Providencia',
        ],
        'sucre' => [
            'en' => 'Sucre',
            'fr' => 'Sucre',
            'nl' => 'Sucre',
            'de' => 'Sucre',
            'es' => 'Sucre',
        ],
        'tolima' => [
            'en' => 'Tolima',
            'fr' => 'Tolima',
            'nl' => 'Tolima',
            'de' => 'Tolima',
            'es' => 'Tolima',
        ],
        'valle-del-cauca' => [
            'en' => 'Valle del Cauca',
            'fr' => 'Valle del Cauca',
            'nl' => 'Valle del Cauca',
            'de' => 'Valle del Cauca',
            'es' => 'Valle del Cauca',
        ],
        'vaupes' => [
            'en' => 'Vaupés',
            'fr' => 'Vaupés',
            'nl' => 'Vaupés',
            'de' => 'Vaupés',
            'es' => 'Vaupés',
        ],
        'vichada' => [
            'en' => 'Vichada',
            'fr' => 'Vichada',
            'nl' => 'Vichada',
            'de' => 'Vichada',
            'es' => 'Vichada',
        ],
        'aysen' => [
            'en' => 'Aysén',
            'fr' => 'Aysén',
            'nl' => 'Aysén',
            'de' => 'Aysén',
            'es' => 'Aysén',
        ],
        'antofagasta' => [
            'en' => 'Antofagasta',
            'fr' => 'Antofagasta',
            'nl' => 'Antofagasta',
            'de' => 'Antofagasta',
            'es' => 'Antofagasta',
        ],
        'arica-y-parinacota' => [
            'en' => 'Arica y Parinacota',
            'fr' => 'Arica y Parinacota',
            'nl' => 'Arica y Parinacota',
            'de' => 'Arica y Parinacota',
            'es' => 'Arica y Parinacota',
        ],
        'la-araucania' => [
            'en' => 'La Araucanía',
            'fr' => 'La Araucanía',
            'nl' => 'La Araucanía',
            'de' => 'La Araucanía',
            'es' => 'La Araucanía',
        ],
        'atacama' => [
            'en' => 'Atacama',
            'fr' => 'Atacama',
            'nl' => 'Atacama',
            'de' => 'Atacama',
            'es' => 'Atacama',
        ],
        'biobio' => [
            'en' => 'Biobío',
            'fr' => 'Biobío',
            'nl' => 'Biobío',
            'de' => 'Biobío',
            'es' => 'Biobío',
        ],
        'coquimbo' => [
            'en' => 'Coquimbo',
            'fr' => 'Coquimbo',
            'nl' => 'Coquimbo',
            'de' => 'Coquimbo',
            'es' => 'Coquimbo',
        ],
        'o-higgins' => [
            'en' => 'O\'Higgins',
            'fr' => 'O\'Higgins',
            'nl' => 'O\'Higgins',
            'de' => 'O\'Higgins',
            'es' => 'O\'Higgins',
        ],
        'los-lagos' => [
            'en' => 'Los Lagos',
            'fr' => 'Los Lagos',
            'nl' => 'Los Lagos',
            'de' => 'Los Lagos',
            'es' => 'Los Lagos',
        ],
        'los-rios' => [
            'en' => 'Los Ríos',
            'fr' => 'Los Ríos',
            'nl' => 'Los Ríos',
            'de' => 'Los Ríos',
            'es' => 'Los Ríos',
        ],
        'magallanes' => [
            'en' => 'Magallanes',
            'fr' => 'Magallanes',
            'nl' => 'Magallanes',
            'de' => 'Magallanes',
            'es' => 'Magallanes',
        ],
        'maule' => [
            'en' => 'Maule',
            'fr' => 'Maule',
            'nl' => 'Maule',
            'de' => 'Maule',
            'es' => 'Maule',
        ],
        'nuble' => [
            'en' => 'Ñuble',
            'fr' => 'Ñuble',
            'nl' => 'Ñuble',
            'de' => 'Ñuble',
            'es' => 'Ñuble',
        ],
        'region-metropolitana' => [
            'en' => 'Santiago Metropolitan Region',
            'fr' => 'Région métropolitaine de Santiago',
            'nl' => 'Metropoolregio Santiago',
            'de' => 'Metropolregion Santiago',
            'es' => 'Región Metropolitana',
        ],
        'tarapaca' => [
            'en' => 'Tarapacá',
            'fr' => 'Tarapacá',
            'nl' => 'Tarapacá',
            'de' => 'Tarapacá',
            'es' => 'Tarapacá',
        ],
        'valparaiso' => [
            'en' => 'Valparaíso',
            'fr' => 'Valparaíso',
            'nl' => 'Valparaíso',
            'de' => 'Valparaíso',
            'es' => 'Valparaíso',
        ],
        'auckland' => [
            'en' => 'Auckland',
            'fr' => 'Auckland',
            'nl' => 'Auckland',
            'de' => 'Auckland',
            'es' => 'Auckland',
        ],
        'bay-of-plenty' => [
            'en' => 'Bay of Plenty',
            'fr' => 'Bay of Plenty',
            'nl' => 'Bay of Plenty',
            'de' => 'Bay of Plenty',
            'es' => 'Bay of Plenty',
        ],
        'canterbury' => [
            'en' => 'Canterbury',
            'fr' => 'Canterbury',
            'nl' => 'Canterbury',
            'de' => 'Canterbury',
            'es' => 'Canterbury',
        ],
        'chatham-islands' => [
            'en' => 'Chatham Islands',
            'fr' => 'Îles Chatham',
            'nl' => 'Chathameilanden',
            'de' => 'Chathaminseln',
            'es' => 'Islas Chatham',
        ],
        'gisborne' => [
            'en' => 'Gisborne',
            'fr' => 'Gisborne',
            'nl' => 'Gisborne',
            'de' => 'Gisborne',
            'es' => 'Gisborne',
        ],
        'hawkes-bay' => [
            'en' => 'Hawke\'s Bay',
            'fr' => 'Hawke\'s Bay',
            'nl' => 'Hawke\'s Bay',
            'de' => 'Hawke\'s Bay',
            'es' => 'Hawke\'s Bay',
        ],
        'marlborough' => [
            'en' => 'Marlborough',
            'fr' => 'Marlborough',
            'nl' => 'Marlborough',
            'de' => 'Marlborough',
            'es' => 'Marlborough',
        ],
        'manawatu-whanganui' => [
            'en' => 'Manawatū-Whanganui',
            'fr' => 'Manawatū-Whanganui',
            'nl' => 'Manawatū-Whanganui',
            'de' => 'Manawatū-Whanganui',
            'es' => 'Manawatū-Whanganui',
        ],
        'nelson' => [
            'en' => 'Nelson',
            'fr' => 'Nelson',
            'nl' => 'Nelson',
            'de' => 'Nelson',
            'es' => 'Nelson',
        ],
        'northland' => [
            'en' => 'Northland',
            'fr' => 'Northland',
            'nl' => 'Northland',
            'de' => 'Northland',
            'es' => 'Northland',
        ],
        'otago' => [
            'en' => 'Otago',
            'fr' => 'Otago',
            'nl' => 'Otago',
            'de' => 'Otago',
            'es' => 'Otago',
        ],
        'southland' => [
            'en' => 'Southland',
            'fr' => 'Southland',
            'nl' => 'Southland',
            'de' => 'Southland',
            'es' => 'Southland',
        ],
        'tasman' => [
            'en' => 'Tasman',
            'fr' => 'Tasman',
            'nl' => 'Tasman',
            'de' => 'Tasman',
            'es' => 'Tasman',
        ],
        'taranaki' => [
            'en' => 'Taranaki',
            'fr' => 'Taranaki',
            'nl' => 'Taranaki',
            'de' => 'Taranaki',
            'es' => 'Taranaki',
        ],
        'wellington' => [
            'en' => 'Wellington',
            'fr' => 'Wellington',
            'nl' => 'Wellington',
            'de' => 'Wellington',
            'es' => 'Wellington',
        ],
        'waikato' => [
            'en' => 'Waikato',
            'fr' => 'Waikato',
            'nl' => 'Waikato',
            'de' => 'Waikato',
            'es' => 'Waikato',
        ],
        'west-coast' => [
            'en' => 'West Coast',
            'fr' => 'West Coast',
            'nl' => 'West Coast',
            'de' => 'West Coast',
            'es' => 'West Coast',
        ],
        'british-columbia' => [
            'en' => 'British Columbia',
            'fr' => 'Colombie-Britannique',
            'nl' => 'Brits-Columbia',
            'de' => 'Britisch-Kolumbien',
            'es' => 'Columbia Británica',
        ],
        'quebec' => [
            'en' => 'Québec',
            'fr' => 'Québec',
            'nl' => 'Quebec',
            'de' => 'Québec',
            'es' => 'Quebec',
        ],
    ];

    public const string REGION_LABELS_SQL = <<<'SQL'
        UPDATE region r SET labels = m.value
        FROM jsonb_each(CAST(:map AS jsonb)) m
        WHERE r.slug = m.key
        SQL;

    #[\Override]
    public function getDescription(): string
    {
        return 'country, country_extract, region.labels: the 19 live countries, from the code lists they replace';
    }

    #[\Override]
    public function up(Schema $schema): void
    {
        foreach (self::COUNTRIES as $code => $c) {
            $this->addSql(
                "INSERT INTO country (code, name, subtype, bbox, labels, timezones, status, seeded_at, live_at)
                 VALUES (:code, :name, :subtype, CAST(:bbox AS jsonb), CAST(:labels AS jsonb),
                         ARRAY(SELECT jsonb_array_elements_text(CAST(:timezones AS jsonb))), 'live',
                         COALESCE((SELECT MIN(created_at) FROM region WHERE country_code = :code), NOW()),
                         COALESCE((SELECT MIN(created_at) FROM region WHERE country_code = :code), NOW()))
                 ON CONFLICT (code) DO NOTHING",
                [
                    'code' => $code,
                    'name' => $c['name'],
                    'subtype' => $c['subtype'],
                    'bbox' => null === $c['bbox'] ? null : json_encode($c['bbox'], \JSON_THROW_ON_ERROR),
                    'labels' => json_encode($c['labels'], \JSON_THROW_ON_ERROR | \JSON_UNESCAPED_UNICODE),
                    'timezones' => json_encode($c['timezones'], \JSON_THROW_ON_ERROR),
                ],
            );
        }
        foreach (self::EXTRACTS as $slug => $cc) {
            $this->addSql(
                'INSERT INTO country_extract (slug, country_code) VALUES (:slug, :cc) ON CONFLICT (slug) DO NOTHING',
                ['slug' => $slug, 'cc' => $cc],
            );
        }
        $this->addSql(self::REGION_LABELS_SQL, ['map' => json_encode(self::REGION_LABELS, \JSON_THROW_ON_ERROR | \JSON_UNESCAPED_UNICODE)]);
    }

    #[\Override]
    public function down(Schema $schema): void
    {
        $this->addSql("UPDATE region SET labels = '{}'::jsonb");
        $this->addSql('DELETE FROM country_extract');
        $this->addSql('DELETE FROM country');
    }
}
