<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260703153611 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE item (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, letter VARCHAR(1) NOT NULL, name VARCHAR(200) NOT NULL, geom geometry(Geometry, 4326) NOT NULL, country_code VARCHAR(2) NOT NULL, subdivision_id BIGINT DEFAULT NULL, region_id BIGINT DEFAULT NULL, state VARCHAR(12) NOT NULL, source VARCHAR(10) NOT NULL, source_ref VARCHAR(160) NOT NULL, attributes JSONB NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, imported_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_item_source_ref ON item (source, source_ref)');
        $this->addSql('CREATE INDEX idx_item_letter_state ON item (letter, state)');
        $this->addSql('CREATE INDEX idx_item_country ON item (country_code)');
        $this->addSql('CREATE INDEX idx_item_region ON item (region_id)');
        $this->addSql('CREATE INDEX idx_item_geom ON item USING GIST (geom)');
        $this->addSql('CREATE TABLE recommended_route (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, geom geometry(Geometry, 4326) NOT NULL, distance_m INT DEFAULT NULL, ascent_m INT DEFAULT NULL, region_id BIGINT DEFAULT NULL, state VARCHAR(12) NOT NULL, source VARCHAR(10) NOT NULL, source_ref VARCHAR(160) NOT NULL, attributes JSONB NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, imported_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_route_source_ref ON recommended_route (source, source_ref)');
        $this->addSql('CREATE INDEX idx_route_region ON recommended_route (region_id)');
        $this->addSql('CREATE INDEX idx_route_geom ON recommended_route USING GIST (geom)');
        $this->addSql('CREATE TABLE heat_point (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, geom geometry(Geometry, 4326) NOT NULL, weight DOUBLE PRECISION NOT NULL, source VARCHAR(10) NOT NULL, computed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_heat_geom ON heat_point USING GIST (geom)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE heat_point');
        $this->addSql('DROP TABLE recommended_route');
        $this->addSql('DROP TABLE item');
    }
}
