<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260703152605 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE region (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(80) NOT NULL, name VARCHAR(160) NOT NULL, geom geometry(Geometry, 4326) DEFAULT NULL, area_km2 DOUBLE PRECISION DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_region_slug ON region (slug)');
        $this->addSql('CREATE INDEX idx_region_geom ON region USING GIST (geom)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE region');
    }
}
