# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# Configuration reference: https://symfony.com/bundles/SchebTwoFactorBundle/index.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

    totp:
        enabled: true
        issuer: 'Cycling Commons'
        template: security/2fa_login.html.twig

    backup_codes:
        enabled: true
