<?php

// SPDX-License-Identifier: AGPL-3.0-only

declare(strict_types=1);

namespace App\Media;

/**
 * Own-work CC BY-SA 4.0 consent. VERSION is the only re-consent trigger.
 *
 * @see docs/specs/photo-uploads.md §1, §4
 *
 * @api
 */
final class MediaConsent
{
    public const string KIND = 'media-cc-by-sa';
    // Wording change must bump VERSION; text_hash is evidence of the exact words.
    /**
     * v6 (2026-10-09): the contract says what the terms say (terms §13): a real
     * place as it was, not generated by AI, nothing added or removed, and
     * ordinary editing and blurring faces and number plates allowed, not
     * required. Bumped because the wording is hashed onto every consent
     * record, and a record has to point at what was actually agreed; earlier
     * records stay valid evidence of their own promise.
     */
    public const string VERSION = 'v6';
    public const string TEXT_KEY = 'media.consent.contract';

    public static function hash(string $text): string
    {
        return hash('sha256', $text);
    }
}
