#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
#
# Writes the Developer Certificate of Origin sign-off into the commit message,
# so nobody has to remember `git commit -s`.
#
# The trailer is the inbound licence grant (CONTRIBUTING.md): it is the author
# saying the work is theirs to give, and agreeing that the licence they grant
# passes to the stichting. .github/workflows/dco.yml refuses any pull-request
# commit without one, and requires it to name that commit's own author.
#
# This hook only ADDS the line. It verifies nothing. A hook runs on the machine
# of whoever chose to install it, so it can never be the gate; the workflow is.
#
# Git calls this with: $1 the message file, $2 the source, $3 the commit SHA.
# pre-commit passes the message file through, and may pass nothing else, so
# only $1 is relied on.
set -euo pipefail

msg_file="${1:?prepare-commit-msg: no message file given}"
[ -f "$msg_file" ] || exit 0

name="$(git config user.name || true)"
email="$(git config user.email || true)"

# No identity, no honest sign-off. Say so rather than writing a broken trailer
# or a silently anonymous one.
if [ -z "$name" ] || [ -z "$email" ]; then
  echo "sign-off: git user.name or user.email is unset, so no Signed-off-by was added." >&2
  echo "  git config user.name  \"Your Name\"" >&2
  echo "  git config user.email \"you@example.com\"" >&2
  exit 1
fi

# A merge's message is generated by git and its commits are already signed off
# on the branch they came from. dco.yml skips merges for the same reason.
if [ -f "$(git rev-parse --git-dir)/MERGE_HEAD" ]; then
  exit 0
fi

# addIfDifferent, not doNothing: an amend or a `git commit -s` already carries
# the trailer and must not gain a second copy, while a co-authored commit that
# carries somebody else's sign-off still needs ours beside it.
git interpret-trailers \
  --in-place \
  --if-exists addIfDifferent \
  --trailer "Signed-off-by: $name <$email>" \
  "$msg_file"
