services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    _instanceof:
        App\Service\UserDeletionHookInterface:
            tags: ['app.user_deletion_hook']

    App\Service\UserDeletionService:
        arguments:
            $hooks: !tagged_iterator app.user_deletion_hook
